USE FantasyTCStore;
GO

CREATE TABLE JOHAN(
    JohanId INT IDENTITY(1,1) NOT NULL
    ,JohanName VARCHAR(1000) NOT NULL
)

ALTER TABLE JOHAN
ADD  CONSTRAINT PK_JOHAN
PRIMARY KEY(JohanId)

SELECT * 
FROM JOHAN;